/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dede_cmake_CMakeLib */

#ifndef _Included_com_dede_cmake_CMakeLib
#define _Included_com_dede_cmake_CMakeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dede_cmake_CMakeLib
 * Method:    memberCallJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dede_cmake_CMakeLib_memberCallJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_dede_cmake_CMakeLib
 * Method:    md5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dede_cmake_CMakeLib_md5
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dede_cmake_CMakeLib
 * Method:    staticCallJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dede_cmake_CMakeLib_staticCallJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
