/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dede_cmake_JavaJNI */

#ifndef _Included_com_dede_cmake_JavaJNI
#define _Included_com_dede_cmake_JavaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dede_cmake_JavaJNI
 * Method:    callJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dede_cmake_JavaJNI_callJNI
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
